### ISSUE TITLE
Not like what I saw...

### ISSUE THREAD

**Issue by CtrlShiftN** [krissss/yii2-log-reader#4]
What expected?
![image](https://user-content.yiiframework.com/img/w4mgXkluPD4DL_2zMIJXvQ/https/github.com/krissss/yii2-log-reader/raw/master/screenshots/preview.png)
What I can see?
![image](https://user-images.githubusercontent.com/22751603/65565397-025a7e80-df7a-11e9-954e-f177073a0f7c.png)
How can I change what I see into what I expected?

**Comment by krissss** [comment]
You cannot visit directly runtime log file.
Please see [Usage](https://github.com/krissss/yii2-log-reader#usage) doc

**Comment by CtrlShiftN** [comment]
Finally, after I install other extensions unsuccessfully, I removed them then back to krissss/yii2-log-reader successfully. However, can you please update it so that user can see more about the error. In this version, you can only see how many errors without its details. We want to see more like that! Thank you...

**Comment by krissss** [comment]
click `view` button in table row can see detail

![image](https://user-images.githubusercontent.com/10680903/65659155-2478fd00-e05d-11e9-824b-397f804f8b96.png)

**Comment by CtrlShiftN** [comment]
It's all logs, what I need is error one only.

**Comment by CtrlShiftN** [comment]
maybe in gridview!

**Comment by krissss** [comment]
> It's all logs, what I need is error one only.

There's no such feature. 
Because view is just send log file to browser with stream and do nothing for this log file.

If you want to see error only in log, you can open file and `ctrl`+`F`, and search `[error]` in view or download it.

Or you can give me some suggestions to do this feature.

**Comment by krissss** [comment]
> It's all logs, what I need is error one only.

There's no such feature. 
Because view is just send log file to browser with stream and do nothing for this log file.

If you want to see error only in log, you can open file and `ctrl`+`F`, and search `[error]` in view or download it.

Or you can give me some suggestions to do this feature.
