### ISSUE TITLE
How to use this feature as login_filter ?

### ISSUE THREAD

**Issue by ghost** [krissss/yii2-log-reader#5]
What exactly needs to be done in this class ? and even if i create and it say object cannot be passed .
```
'as login_filter' => UserLoginFilter::class, // to use login filter
````

**Comment by krissss** [comment]
`as xxx` is a configuration in Yii2 to attach behavior , see [this](https://www.yiiframework.com/doc/guide/2.0/en/concept-behaviors#attaching-behaviors)

This is used because access to this route typically requires a login. And `UserLoginFilter` did this filter.

**Comment by ghost** [comment]
Thanks a lot mate I have used in this way . I was not extending it with the `Behavior` class .
```
<?php
namespace app\base\filters;

use yii\base\Behavior;
use yii\web\HttpException;

class UserLoginFilter extends Behavior
{
    public function __construct()
    {
        if(CheckIfUserIsAdmin){
            throw new HttpException(403, \Yii::t('app', 'You do not have access.'));
        }
    }

}
```

**Comment by krissss** [comment]
```php
class UserLoginFilter extends ActionFilter
{
    /**
     * no Login to redirect
     * @var array
     */
    public $loginUrl = ['/site/login'];

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            Yii::$app->getResponse()->redirect($this->loginUrl);
            return false;
        }
        return parent::beforeAction($action);
    }
}
```

Better to use [`ActionFilter`](https://www.yiiframework.com/doc/guide/2.0/en/structure-filters)

**Comment by ghost** [comment]
Yeah it actually does make scene Thanks mate .
