### ISSUE TITLE
Error trying to install this extension with composer

### ISSUE THREAD

**Issue by lloyd966** [krissss/yii2-log-reader#6]
I get the following error when I try to install your yii2-log-reader extension

C:\wamp64\www\pmtts>composer require --prefer-dist kriss/yii2-log-reader "2.4" --ignore-platform-reqs
./composer.json has been updated
Running composer update kriss/yii2-log-reader
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kriss/yii2-log-reader, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Any help in getting this extension installed would be very much appreciated.

Thank you

Lloyd

**Comment by krissss** [comment]
I installed it successfully with your command: `composer require --prefer-dist kriss/yii2-log-reader "2.4" --ignore-platform-reqs`

Please check your packagist repo with `composer global config -l`

**Comment by lloyd966** [comment]
Thank you for your quick response.

I ran the following as per your response 

composer global config -l 
composer require --prefer-dist kriss/yii2-log-reader "2.4" --ignore-platform-reqs 

And I still get the same error.
I do not have very much experience with composer. Any other suggestions would be greatly appreciated.

Thank you

**Comment by krissss** [comment]
put your result with command: composer global config -l

**Comment by lloyd966** [comment]
Below is the result from the command: composer global config -l

C:\wamp64\www\pmtts>composer global config -l
Changed current directory to C:/Users/Lloyd/AppData/Roaming/Composer
[repositories.packagist.org.type] composer
[repositories.packagist.org.url] https://repo.packagist.org
[process-timeout] 300
[use-include-path] false
[allow-plugins]
[use-parent-dir] prompt
[preferred-install] dist
[notify-on-install] true
[github-protocols] [https, ssh]
[gitlab-protocol]
[vendor-dir] vendor (C:\Users\Lloyd\AppData\Roaming\Composer/vendor)
[bin-dir] {$vendor-dir}/bin (C:\Users\Lloyd\AppData\Roaming\Composer/vendor/bin)
[cache-dir] C:/Users/Lloyd/AppData/Local/Composer
[data-dir] C:/Users/Lloyd/AppData/Roaming/Composer
[cache-files-dir] {$cache-dir}/files (C:/Users/Lloyd/AppData/Local/Composer/files)
[cache-repo-dir] {$cache-dir}/repo (C:/Users/Lloyd/AppData/Local/Composer/repo)
[cache-vcs-dir] {$cache-dir}/vcs (C:/Users/Lloyd/AppData/Local/Composer/vcs)
[cache-ttl] 15552000
[cache-files-ttl] 15552000
[cache-files-maxsize] 300MiB (314572800)
[cache-read-only] false
[bin-compat] auto
[discard-changes] false
[autoloader-suffix]
[sort-packages] false
[optimize-autoloader] false
[classmap-authoritative] false
[apcu-autoloader] false
[prepend-autoloader] true
[github-domains] [github.com]
[bitbucket-expose-hostname] true
[disable-tls] false
[secure-http] true
[cafile]
[capath]
[github-expose-hostname] true
[gitlab-domains] [gitlab.com]
[store-auths] prompt
[archive-format] tar
[archive-dir] .
[htaccess-protect] true
[use-github-api] true
[lock] true
[platform-check] php-only
[home] C:/Users/Lloyd/AppData/Roaming/Composer

C:\wamp64\www\pmtts>

**Comment by krissss** [comment]
Its correct
try this command: `composer require kriss/yii2-log-reader --ignore-platform-reqs`
or put your `composer.json` which in path your composer exec (may be in `C:\wamp64\www\pmtts>`)

**Comment by lloyd966** [comment]
Hi

I get an error when i try the following

C:\wamp64\www\pmtts>composer require kriss/yii2-log-reader --ignore-platform-reqs

In PackageDiscoveryTrait.php line 375:

  Could not find a matching version of package kriss/yii2-log-reader. Check the package spelling, your version constraint and that the package is available in a stability w
  hich matches your minimum-stability (dev).


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]


C:\wamp64\www\pmtts>


Sorry for all the questions, but your help is greatly appreciated.

**Comment by krissss** [comment]
put your composer.json which in path your composer exec (may be in C:\wamp64\www\pmtts>)

**Comment by lloyd966** [comment]
I have the following composer files in two locations as follows:

C:\wamp64\www\pmtts
composer.json                      5kb
composer.lock                   432kb

C:\
composer.json                      1kb
composer.lock                    23kb

Just to clarify are you suggesting that I copy the 2 composer files from  C:\wamp64\www\pmtts and overwrite the 2 composer files in C:\ ?

**Comment by krissss** [comment]
no
I think you should learn composer usage first...
I cant help you

**Comment by lloyd966** [comment]
I understand.

Thank you for all your help.
